Feature/new timeline chart
CSIS-iLab/missilethreat_timeline pull request #15
Opened 2019-11-26 18:32 UTC by urchykli

2019-12-02 21:26 UTC, urchykli commented
Changes:
- Created Google sheet that parses the data and will update automatically
- Add link to sheet
- Change title font
- Remove subtitle on export
- Change credits to Missile Threat url on export

2019-12-06 20:04 UTC, smaraghi commented on hc-bar/js/bar.js
> +    var event = "";
I believe that this event object is never used in the code. Please remove it as its value is never read.

2019-12-06 20:08 UTC, smaraghi commented on hc-bar/js/bar.js
> +      // var eventText = row[10]
Lets remove this code comment (var eventText...)

2019-12-06 21:26 UTC, smaraghi requested changes
Thank you for all of your hard work!!

Please remove unnecessary code comments as well as the object referenced below.

Thanks!

2019-12-06 21:35 UTC, urchykli commented
Removed unused event variable and unnecessary code comments

2019-12-06 22:01 UTC, smaraghi approved these changes

2019-12-06 22:08 UTC, merged